general.import = [
"~/.config/alacritty/alacritty/catppuccin-mocha.toml"
]

[font]
size = 16

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[scrolling]
history = 0

[window]
opacity = 0.92

[terminal]
osc52 = "CopyPaste"
