#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Reclaim any old windows (but lose their positions)
bspc wm --adopt-orphans

# Set up the window padding
bspc config border_width        2
bspc config window_gap          5
bspc config left_padding        0
bspc config right_padding       0
bspc config top_padding         ${BAR_HEIGHT}
bspc config bottom_padding      0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Prevents changing focus with the mouse pointer
bspc config focus_follows_pointer false

# Color scheme configuration
bspc config focused_border_color   "#ff0000"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

